### ISSUE TITLE
Bug in the "Create master gear" tool in FreeCAD 0.20.2

### ISSUE THREAD

**Issue by andesfreedesign** [sebasg84/InvGears#8]
Traceback (most recent call last):
  File "/.local/share/FreeCAD/Mod/InvGears/./freecad/invgears/newMasterCmd.py", line 46, in accept
    self.createInvoluteGears()
  File "/.local/share/FreeCAD/Mod/InvGears/./freecad/invgears/newMasterCmd.py", line 92, in createInvoluteGears
    SlaveGear(fp_slave, fp_master, angle)
  File "/.local/share/FreeCAD/Mod/InvGears/./freecad/invgears/featureClasses.py", line 111, in __init__
    slavePartExpressions(fp, fp_master)
  File "/.local/share/FreeCAD/Mod/InvGears/./freecad/invgears/expressions.py", line 85, in slavePartExpressions
    part_slave.setExpression("Placement", f"create(<<placement>>; create(<<vector>>; {xp}; {yp}; {zp}); create(<<rotation>>; create(<<vector>>; 0; 0; 1); {angle}))")
<class 'Base.ParserError'>: Failed to parse expression.

**Comment by Durksz** [comment]
I've managed to fix the bug. my fork has the fix. I've proposed the change to be merged into the main
